### ISSUE TITLE
Brushstroke erroneously overpaints the same x,y co-ordinates

### ISSUE THREAD

**Issue by Jetroid** [lmgonzalves/brushstroke#4]
Hey @lmgonzalves, I love what you've made here.

I'm wondering if it is possible to prevent the 'stubbing' in the brushstrokes.

Fairly consistently in my brushstrokes, the line looks beautiful right up until it stops drawing, at which point it becomes a lot thicker and 'dottier'. 

The same kind of 'dottiness' also happens a lot during straight lines (with just two points).

I have cherry picked an example, picture attached.

![2020-12-16-173325_555x191_scrot](https://user-images.githubusercontent.com/8970691/102384596-d420ee80-3fc4-11eb-90d7-468b2af398b4.png)

It almost looks like what happens in a paint application when you use a spray can tool and don't move the cursor; makes me wonder if brushstroke is painting for an extra frame or two without moving / after it has finished moving? 

I tested this theory by making it so that the Brush's render method doesn't render if it has already painted on a given x,y pair, basically by putting the following at the top of the method:

```
if(this.hadPoints.includes(x+","+y)) {
    return;
}
this.hadPoints.push(x+","+y);
``` 
(obviously also adding a new hadPoints member to Brush (initially as an empty array))

The result was greatly improved (and performance was better on my slow device, actually):

![2020-12-16-173145_534x154_scrot](https://user-images.githubusercontent.com/8970691/102384802-03376000-3fc5-11eb-97c8-90509101312c.png)

My solution is very crude, so I'm wondering if you have any insight into why this is happening that could help us to solve it in a more elegant way?

**Comment by lmgonzalves** [comment]
Hey @Jetroid, thanks, nice work improving the rendering!
Can you please share your example demo in [codepen](https://codepen.io/) or [jsfiddle](https://jsfiddle.net/)?
I don't have too much time, but that way I could take a quick look and see how the library can be improved.
Thanks!

**Comment by Jetroid** [comment]
Sure, [here's a version with the official code](https://jsfiddle.net/Jetroid/d60tqb58/6/), and here's a version with [my modification applied](https://jsfiddle.net/Jetroid/d60tqb58/9/).

I've realised that we only need to refer to the last point that we painted rather than keeping track of every point from the history. Therefore, the modification is now as simple as adding the following to line [197](https://github.com/lmgonzalves/brushstroke/blob/master/js/brushstroke.js#L197):

```
if(this._latestPos.x === this.x && this._latestPos.y === this.y) {
    return;
}
```

Let me know what you think; if you like the change, I'll submit a pull request shortly.

**Comment by lmgonzalves** [comment]
Nice!
Yes, please send a PR, I will be happy to merge :)
